"allow_contract_creation": true


whitelist:
  - address: "0x111C3E89Ce80e62EE88318C2804920D4c96f92bb"
    fully_whitelisted: true

  - address: "0x4B5DF730c2e6b28E17013A1485E5d9BC41Efe021"
    fully_whitelisted: false
    methods:
      unrestricted:
      # totalSupply()
        - "18160ddd"
      requires_authorization:
        # balanceOf(address)
        - "70a08231"