"allow_contract_creation": true


whitelist:
  - address: "0x111C3E89Ce80e62EE88318C2804920D4c96f92bb"
    fully_whitelisted: true

  - address: "0x26b368C3Ed16313eBd6660b72d8e4439a697Cb0B"
    fully_whitelisted: false
    methods:
      unrestricted:
      # totalSupply()
        - "18160ddd"
      requires_authorization:
        # balanceOf(address)
        - "70a08231"